<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<title>$ - Hoogle</title>
		<link type="text/css" rel="stylesheet" href="res/hoogle.css" />

		<script type="text/javascript">
		function on_load()
		{
			document.getElementById('txt').focus();
		}
		</script>
	</head>
	<body onload="on_load()" id="answers">

<div id="logo">
	<a href=".">
		<img src="res/hoogle_small.png" alt="Hoogle" />
	</a>
</div>

<form action="?" method="get">
	<div>
		<input name="q" id="txt" type="text" style="width:300px;margin-right:5px;" value="$" />
		<input style="padding-left:15px;padding-right:15px;" type="submit" value="Search" />
	</div>
</form>

